---
title: "Konsolide Kamu Sektörü Gerçekleşmeleri"
author: 
  - Afranur Melek Çevik [^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080561, [Github Repo](https://github.com/aframelek/arasinav)

# Vize Hakkında Önemli Bilgiler

\colorbox{BurntOrange}{GITHUB REPO BAĞLANTINIZI BU DOSYANIN 35. SATIRINA YAZINIZ!}

**Proje önerisi gönderimi, Github repo linki ile birlikte ekampus sistemine bir zip dosyası yüklenerek yapılacaktır. Sisteme zip dosyası yüklemezseniz ve Github repo linki vermezseniz ara sınav ve final sınavlarına girmemiş sayılırsınız.**

**Proje klasörünüzü sıkıştırdıktan sonra (`YourStudentID.zip` dosyası) 16 Nisan 2023 23:59'a kadar *ekampus.ankara.edu.tr* adresine yüklemeniz gerekmektedir.**

\colorbox{WildStrawberry}{Daha fazla bilgi için proje klasöründeki README.md dosyasını okuyunuz.}

# Giriş
Bu taslak size proje ödevinizi yazarken yardımcı olması amacıyla oluşturulmuştur. Ödevlerinizde, makalelerinizde, sunumlarınızda ve projelerinizde kullandığınız tüm bilgi kaynaklarına atıfta bulunmalısınız. Alıntı ve gönderme yapmak okuyuculara çalışmanızda kullandığınız/başvurduğunuz  kaynaklara ulaşma imkanı sağlar. **Her ne kadar kendi sözlerinizi kullanıyor olsanız da, başkalarına ait fikirleri çalışmanızda aktarıyorsanız bu fikirlerin kaynağını belgelemek zorundasınız. Aksi takdirde akademik intihal yapmış olursunuz.** 


Proje ödevinizde yer alan başlıkların bu metinde yer alan başlıkları kesinlikle içermesi gerekmektedir (doğal olarak ilk bölüm başlığı hariç). Burada kullanılan başlıklar haricinde farklı alt başlıklar da kullanabilirsiniz. Projenizi yazarken bu dosyayı taslak olarak kullanıp içeriğini projenize uyarlayınız.

## Çalışmanın Amacı
Konsolide kamu sektörü gerçekleşmeleri, bir ülkenin tüm kamu kesimine (merkezi yönetim, yerel yönetimler, sosyal güvenlik kurumları) ait bütçe ve mali verilerin bir araya getirilerek toplamda elde edilen sonuçları ifade eder. Konssolide kamu sektörü gerçekleşmeleri, genellikle kamu maliyesi ve ekonomi politikası alanında yapılan analizlerde, bütçe politikalarının etkilerini değerlendirmek için önemli bir veri kaynağı olarak kullanılır. Ben 2004-2012 yılları arasını ele alan tablomu tüik kamu finansmanı istatislikleri hazine maliye bakanlığından ([T.C Hazine ve Maliye Bakanlığı](https://www.hmb.gov.tr/kamu-finansmani-istatistikleri)) buldum. Çalışmamda bir ülkenin genel mali durumunu, bütçe dengesini, borçlanma ve finansman durumunu değerlendiriyorum.

## Literatür 
Arastırmamda bulduğum makalelerimde ortak olarak ülkenin tüm kamu kesimine ait bütçe ve mali verilerin bir araya getirilmesinden bahsediliyor. [@ozdenkamu,] makalesinde öncelikli olarak borçlanma konusunu ele alıyor. Ülkenin borçlanma serüvenini tarihsel olarak ortaya koyuyor. Ülke ekonomisinin dengede olabilmesi için, ekonomik kalkınmanın sağlanıp sürdürülebilmesi için iç ve dış borçlanmanın dengesinden bahsediyor. Türkiye IMF ilişkisini ele alıyor. Ülkeler kaynaklar konusunda yetersiz kalınca iç ve dış borçlanmayla bu sorunu halletmeye çalışıyor. Bozulan dengeler tekrar düzeltilebir. bunun için yeniden borçlanmaya basvuruluyor. bu çalışmada kamu kesimi borçlanma gereği açısından Türkiye-IMF ilişkileri 2001 sonrası dönem itibari ile ele alınmakta.Bu makalemde de [@ccakir2020turkiye,] Türkiye de kamu kesimi açıkları finanmanının en çok başvurduğu yöntemin borçlanma olduğunu ve bunun dünya genelinde de aynı olduğunu anlatıyor.Çalışma Türkiye’nin 1990-2015 döneminde kamu finansman dengelerinin gelişimi ve borçlanma politikalarının kamu finansman dengelerine etkisi inceliyor. Ek olarak [@grossi2015pursuing,] ve [@almquist2013public,] yazılarda da kamu sektörünün mali ve ekonomik incelemelerinden bahsediliyor.


**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>
([Makale!](https://acikbilim.yok.gov.tr/handle/20.500.12812/584144))
([Makale2!](https://dergipark.org.tr/en/pub/susead/article/629115))
([Makale3!](https://www.sciencedirect.com/science/article/abs/pii/S1045235412001207))
([Makale4!](https://www.tandfonline.com/doi/abs/10.1080/01900692.2015.1001239))
([Veritablosu!](https://www.hmb.gov.tr/kamu-finansmani-istatistikleri))


